# 截止日期，默认为当天，日期格式为 2023-01-20
end_date: ''
ma:
  # 计算多少日MA均线，默认250天
  days: 250
  # 是否只计算MA呈上升趋势的，1表示是，0表示否，默认为1
  trend_raise: 1
  # MA的浮动区间，默认10%
  percent: 0.1
# 计算几日内有MACD金叉，默认3天
macd_cross_days: 3
# 计算几日内有KDJ金叉，默认3天
kdj_cross_days: 3
